apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../release
configMapGenerator:
- name: pvpool-controller-config
  behavior: merge
  literals:
  - debug=true
configMapGenerator:
- name: pvpool-webhook-config
  behavior: merge
  literals:
  - debug=true
