apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvpool-controller
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        pvpool.puppet.com/debug: "false"
    spec:
      serviceAccountName: pvpool-controller
      containers:
      - name: pvpool-controller
        image: ko://github.com/puppetlabs/pvpool/cmd/pvpool-controller
        env:
        - name: PVPOOL_DEBUG
          valueFrom:
            fieldRef:
              fieldPath: "metadata.annotations['pvpool.puppet.com/debug']"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: [all]
          runAsUser: 65532
          runAsGroup: 65532
