apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvpool-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      pvpool.puppet.com/selector: pvpool-controller
  template:
    metadata:
      annotations:
        pvpool.puppet.com/config.debug: "false"
      labels:
        pvpool.puppet.com/selector: pvpool-controller
    spec:
      serviceAccountName: pvpool-controller
      containers:
      - name: pvpool-controller
        image: ko://github.com/puppetlabs/pvpool/cmd/pvpool-controller
        env:
        - name: PVPOOL_DEBUG
          valueFrom:
            fieldRef:
              fieldPath: "metadata.annotations['pvpool.puppet.com/config.debug']"
        - name: PVPOOL_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: PVPOOL_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: [all]
          runAsUser: 65532
          runAsGroup: 65532
