apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- generated/role.yaml
- serviceaccount.yaml
- clusterrolebinding.yaml
- deployment.yaml
configurations:
- kustomizeconfig/nameprefix.yaml
commonLabels:
  app.kubernetes.io/name: pvpool
  app.kubernetes.io/component: controller
  app.kubernetes.io/instance: pvpool-controller
