apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../crd
- ../controller
- ../webhook-autocert
transformers:
- kustomizeconfig/label-version.yaml
namespace: pvpool
namePrefix: default-
commonLabels:
  app.kubernetes.io/name: pvpool
configMapGenerator:
- name: pvpool-environment
  envs:
  - environment.properties
generatorOptions:
  disableNameSuffixHash: true
vars:
- name: PVPOOL_VERSION
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: pvpool-environment
  fieldref:
    fieldpath: data.PVPOOL_VERSION
