apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- external
- role.yaml
- serviceaccount.yaml
- clusterrolebinding.yaml
- rolebinding.yaml
- deployment.yaml
configMapGenerator:
- name: pvpool-webhook-certificate-controller-config
  files:
  - _examples=configmap-config-_examples.txt
commonLabels:
  app.kubernetes.io/name: pvpool
  app.kubernetes.io/component: webhook-certificate-controller
  app.kubernetes.io/instance: pvpool-webhook-certificate-controller
