apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pvpool-webhook-certificate-controller
rules:
- apiGroups: [""]
  resources: [secrets]
  verbs: [create]
- apiGroups: [""]
  resources: [events]
  verbs: [create, patch]
- apiGroups: [coordination.k8s.io]
  resources: [leases]
  verbs: [get, list, watch, create, update, delete]
