apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvpool-webhook-certificate-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      pvpool.puppet.com/selector: pvpool-webhook-certificate-controller
  template:
    metadata:
      annotations:
        pvpool.puppet.com/config.debug: "false"
        pvpool.puppet.com/config.webhook-service-name: webhook-service
        pvpool.puppet.com/config.webhook-certificate-secret-name: pvpool-webhook-certificate
        pvpool.puppet.com/config.validating-webhook-configuration-name: validating-webhook-configuration
      labels:
        pvpool.puppet.com/selector: pvpool-webhook-certificate-controller
    spec:
      serviceAccountName: pvpool-webhook-certificate-controller
      containers:
      - name: pvpool-webhook-certificate-controller
        image: ko://github.com/puppetlabs/pvpool/cmd/pvpool-webhook-certificate-controller
        env:
        - name: PVPOOL_DEBUG
          valueFrom:
            fieldRef:
              fieldPath: "metadata.annotations['pvpool.puppet.com/config.debug']"
        - name: PVPOOL_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: PVPOOL_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PVPOOL_WEBHOOK_SERVICE_NAME
          valueFrom:
            fieldRef:
              fieldPath: "metadata.annotations['pvpool.puppet.com/config.webhook-service-name']"
        - name: PVPOOL_WEBHOOK_CERTIFICATE_SECRET_NAME
          valueFrom:
            fieldRef:
              fieldPath: "metadata.annotations['pvpool.puppet.com/config.webhook-certificate-secret-name']"
        - name: PVPOOL_VALIDATING_WEBHOOK_CONFIGURATION_NAME
          valueFrom:
            fieldRef:
              fieldPath: "metadata.annotations['pvpool.puppet.com/config.validating-webhook-configuration-name']"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: [all]
          runAsUser: 65532
          runAsGroup: 65532
