apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../webhook
- ../webhook-certificate-controller
configurations:
- kustomizeconfig/nameprefix.yaml
- kustomizeconfig/namereference.yaml
configMapGenerator:
- name: pvpool-webhook-config
  behavior: merge
  literals:
  - certificate-secret-name=pvpool-webhook-certificate
- name: pvpool-webhook-certificate-controller-config
  behavior: merge
  literals:
  - certificate-secret-name=pvpool-webhook-certificate
  - service-name=webhook-service
  - validating-webhook-configuration-name=validating-webhook-configuration
