apiVersion: v1
kind: Service
metadata:
  # Note that this name aligns to the name in the generated admission manifests,
  # which we then replace with a patch later once name reference resolution is
  # complete.
  name: webhook-service
spec:
  ports:
  - name: https
    port: 443
    targetPort: https
